"""add key_focus, task_key_focus, and blocker tables

Revision ID: 3f33f977ca96
Revises: 00f312b05b23
Create Date: 2026-04-07 22:12:57.406598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f33f977ca96'
down_revision: Union[str, None] = '00f312b05b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_focus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('delivery', 'learning', 'support', 'operational', 'side_quest', name='keyfocuskind'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'succeed', 'failed', name='keyfocusstatus'), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'quarterly', name='keyfocusfrequency'), nullable=False),
    sa.Column('weekly_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_id'], ['weekly.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('opened', 'resolved', name='blockerstatus'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('key_focus_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(task_id IS NOT NULL AND key_focus_id IS NULL) OR (task_id IS NULL AND key_focus_id IS NOT NULL)', name='ck_blocker_xor_reference'),
    sa.ForeignKeyConstraint(['key_focus_id'], ['key_focus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_key_focus',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('key_focus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_focus_id'], ['key_focus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'key_focus_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_key_focus')
    op.drop_table('blocker')
    op.drop_table('key_focus')
    # ### end Alembic commands ###
