"""initial tables

Revision ID: d8ae591b34ad
Revises: 
Create Date: 2026-03-29 18:29:11.986231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ae591b34ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jira_ticket_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('refinement', 'implementation', 'review', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('created', 'done', name='taskstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_table('daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weekly_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_id'], ['weekly.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('daily_tasks',
    sa.Column('daily_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_id'], ['daily.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_id', 'task_id'),
    sa.UniqueConstraint('daily_id', 'priority', name='uq_daily_priority')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_tasks')
    op.drop_table('daily')
    op.drop_table('weekly')
    op.drop_table('task')
    # ### end Alembic commands ###
