"""add_worker_repository_tables

Revision ID: e4666bd8e9fd
Revises: 3f33f977ca96
Create Date: 2026-04-13 21:47:54.231924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4666bd8e9fd'
down_revision: Union[str, None] = '3f33f977ca96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('git_url', sa.Text(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_url', 'branch', name='uq_repository_git_url_branch')
    )
    op.create_table('worker',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('claude_code', name='workertype'), nullable=False),
    sa.Column('state', sa.Enum('initialized', 'working', 'waiting_for_human', 'done', 'archived', name='workerstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('worker_repository',
    sa.Column('worker_id', sa.String(length=32), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'repository_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_repository')
    op.drop_table('worker')
    op.drop_table('repository')
    # ### end Alembic commands ###
