apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: file:///mnt/jarvis-repo
    path: helm/jaar
    targetRevision: HEAD
    helm:
      releaseName: jaar
      valuesObject: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: jaar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
