apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: file:///mnt/jarvis-repo
    path: secrets
    targetRevision: HEAD
    directory:
      recurse: false
      include: "backend-secret.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
