apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jarvis-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: "*.jarvis.io"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.jarvis.io"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: jarvis-io-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: localhost
      port: 80
      protocol: HTTP
      hostname: "localhost"
      allowedRoutes:
        namespaces:
          from: All
