apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
type: Opaque
data:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
