{{- if .Values.persistence.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-sqlite
  labels:
    app: {{ .Release.Name }}-backend
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-sqlite
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-sqlite
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.hostPath }}
  storageClassName: ""
  volumeName: {{ .Release.Name }}-sqlite
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
