apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-worker-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "list", "delete"]
