# Default values for jarvis chart.

backend:
  image:
    repository: ghcr.io/alchemesh-io/jarvis-backend
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 8000
  resources: {}
  config:
    databaseUrl: "sqlite:////data/jarvis.db"
    appTitle: "J.A.R.V.I.S"
    debug: "false"
  secrets: {}

frontend:
  image:
    repository: ghcr.io/alchemesh-io/jarvis-frontend
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
  resources: {}

mcp:
  image:
    repository: ghcr.io/alchemesh-io/jarvis-mcp
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  backendUrl: ""
  resources: {}

persistence:
  storageClass: standard
  size: 1Gi
